kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-deltaker
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-deltaker.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 45
    periodSeconds: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    outbound:
      rules:
        - application: amt-person-service
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: nav-dev
  env:
    - name: AMT_PERSONSERVICE_SCOPE
      value: api://dev-gcp.amt.amt-person-service/.default
    - name: AMT_PERSONSERVICE_URL
      value: http://amt-person-service

  gcp:
    sqlInstances:
      - name: amt-deltaker
        collation: nb_NO.UTF8
        type: POSTGRES_14
        databases:
          - name: amt-deltaker
            envVarPrefix: DB
